// The combat half of the adjudication catalog: everything a DM does with a
// fight running. Names match the tool names the AI DM is offered exactly,
// because both callers reach the same engine
// (src/lib/dm/invoke.ts). The board's entries (pets, tokens, legendary
// creatures) live in catalog-board.ts and are spread in at the end.
import type { CatalogEntry } from "@/lib/dm/catalog-types";
import { BOARD_ADJUDICATIONS } from "@/lib/dm/catalog-board";
import { summonFormNames } from "@/lib/srd/summon-forms";
import { familiarFormNames } from "@/lib/srd/familiar-forms";
import { BEAST_FORMS } from "@/lib/srd/beast-forms";
import {
  ABILITY_OPTIONS as ABILITIES,
  AREA_PLACEMENT_FIELDS,
  REASON_FIELD as REASON,
  TRAP_SEVERITY_OPTIONS,
  advantageFields,
  conditionField,
  damageTypeField,
} from "@/lib/dm/catalog-vocab";

const BONUS_ATTACK = [
  { value: "martial arts", label: "Martial Arts strike" },
  { value: "frenzy", label: "Frenzy" },
  // A subclass's bonus weapon attack (Battle Magic, War Magic, Sudden Strike): authored-effects.ts.
  { value: "feature", label: "Subclass feature" },
];

// Open Hand Technique's three riders, the pc_attack schema's OPEN_HAND_CHOICES.
const OPEN_HAND = [
  { value: "prone", label: "Knock prone (DEX save)" },
  { value: "push", label: "Push 15 feet (STR save)" },
  { value: "no reactions", label: "No reactions until the monk's next turn ends" },
];

// The reactions the engine resolves by name (src/lib/dm/reaction-tools.ts).
const REACTIONS = [
  { value: "Shield", label: "Shield" },
  { value: "Uncanny Dodge", label: "Uncanny Dodge" },
  { value: "Deflect Missiles", label: "Deflect Missiles" },
  { value: "Cutting Words", label: "Cutting Words" },
  { value: "Protection", label: "Protection" },
  { value: "Slow Fall", label: "Slow Fall" },
  { value: "Feather Fall", label: "Feather Fall" },
  { value: "Hellish Rebuke", label: "Hellish Rebuke" },
  { value: "Counterspell", label: "Counterspell" },
  { value: "Opportunity attack", label: "Opportunity attack (off the map)" },
];

export const COMBAT_ADJUDICATIONS: CatalogEntry[] = [
  {
    name: "start_encounter",
    label: "Start a fight",
    category: "combat",
    summary: "Rolls initiative for everyone and opens the encounter.",
    fields: [
      {
        name: "enemies",
        label: "Enemies",
        kind: "longtext",
        required: true,
        placeholder: "goblin x4\nhobgoblin",
        help: "One per line, name or SRD slug, optional xN for a count. Stat blocks come from the content pack.",
      },
      { name: "summary", label: "Opening", kind: "text" },
      {
        name: "ambush",
        label: "Ambush",
        kind: "select",
        options: [
          { value: "enemies", label: "The enemies lie in wait" },
          { value: "party", label: "The party springs it" },
        ],
        help: "The server rolls the hiders' Stealth against each opponent's passive Perception; only those who notice nothing are surprised.",
      },
      {
        name: "surprised",
        label: "Or decide surprise",
        kind: "select",
        options: [
          { value: "none", label: "Nobody" },
          { value: "enemies", label: "The enemies are surprised" },
          { value: "party", label: "The party is surprised" },
        ],
        help: "Overrides the ambush roll for a whole side.",
      },
      { name: "battlefield", label: "Battlefield", kind: "text" },
      {
        name: "distanceFeet",
        label: "Opening distance (feet)",
        kind: "number",
        min: 5,
        max: 600,
        help: "How far the nearest enemy stands from the party. Empty, the sides open across the field.",
      },
      {
        name: "lair",
        label: "In a legendary creature's lair",
        kind: "boolean",
        help: "The lair acts on initiative 20 each round (Lair action).",
      },
    ],
  },
  {
    name: "add_enemies",
    label: "Reinforcements",
    category: "combat",
    summary: "Adds enemies to the fight already running, rolling their initiative in.",
    needsEncounter: true,
    fields: [
      {
        name: "enemies",
        label: "Enemies",
        kind: "longtext",
        required: true,
        placeholder: "wolf x2",
      },
      REASON,
    ],
  },
  {
    name: "pc_attack",
    label: "Player attacks",
    category: "combat",
    summary: "Resolves a player's swing: to hit, damage, crits, riders, all from their sheet.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Attacker", kind: "character", required: true },
      { name: "targetEnemyId", label: "Target", kind: "enemy", required: true },
      { name: "weapon", label: "Weapon", kind: "text", help: "From their equipment. Blank uses the best weapon they carry." },
      { name: "spell", label: "Attack spell", kind: "text", help: "An attack-roll spell instead of a weapon, such as Fire Bolt. It takes the whole action." },
      { name: "damage", label: "Spell damage", kind: "dice", placeholder: "1d10", help: "Only for a spell the content pack does not know." },
      damageTypeField("damageType", "Spell damage type"),
      { name: "level", label: "Spell slot level", kind: "number", min: 1, max: 9, help: "An attack spell of 1st level or higher: the slot cast from. Empty uses the spell's own level." },
      ...advantageFields(),
      { name: "twoHanded", label: "In both hands", kind: "boolean", help: "A versatile weapon rolls its bigger die. Not with a shield on the arm." },
      { name: "offHand", label: "Off-hand attack", kind: "boolean", help: "The bonus action of two-weapon fighting, after an attack with a light weapon." },
      { name: "smite", label: "Divine Smite slot", kind: "number", min: 1, max: 9, help: "Paladin only. The slot is spent if the attack hits." },
      { name: "maneuver", label: "Maneuver", kind: "text", help: "Battle Master only. The Superiority Die is spent on a hit (on the roll for Precision Attack)." },
      { name: "bonusAttack", label: "Bonus-action attack", kind: "select", options: BONUS_ATTACK, help: "Martial Arts' unarmed strike after the Attack action, or a raging Berserker's frenzy. Spends the bonus action." },
      { name: "stunningStrike", label: "Stunning Strike", kind: "boolean", help: "Monk 5+. One ki on a melee hit; the target saves CON or is stunned." },
      { name: "powerAttack", label: "Power attack (-5 / +10)", kind: "boolean", help: "Great Weapon Master with a heavy melee weapon, or Sharpshooter with a ranged weapon: -5 to hit for +10 damage." },
      { name: "reckless", label: "Reckless Attack", kind: "boolean", help: "Barbarian 2+, first attack of the turn. Attacks against them have advantage until their next turn." },
      { name: "nonlethal", label: "Knock out", kind: "boolean", help: "Melee only. A creature dropped to 0 falls unconscious instead of dying." },
      { name: "hordeBreaker", label: "Horde Breaker", kind: "boolean", help: "Hunter ranger, once a turn: an extra attack on a different creature within 5 feet of one already attacked." },
      { name: "useInspiration", label: "Spend their Inspiration", kind: "boolean", help: "Advantage on this attack roll. Refused when they hold none." },
      { name: "strokeOfLuck", label: "Stroke of Luck", kind: "boolean", help: "Rogue 20: a miss becomes a hit and spends the use (once a short rest); a hit spends nothing." },
      {
        name: "openHand",
        label: "Open Hand Technique",
        kind: "select",
        options: OPEN_HAND,
        help: "Way of the Open Hand, on a Flurry of Blows strike only. The server rolls the target's save against the ki DC.",
      },
      { name: "hurlThroughHell", label: "Hurl Through Hell", kind: "boolean", help: "Fiend warlock 14, on a hit: gone until the end of the warlock's next turn, then 10d10 psychic unless a fiend. Once a long rest." },
      { name: "rapidStrike", label: "Rapid Strike", kind: "boolean", help: "Samurai 15, once a turn: an attack with advantage gives it up for one more attack of the Attack action." },
      { name: "whirlwind", label: "Whirlwind Attack", kind: "boolean", help: "Hunter 11: the action makes one melee attack against each creature within 5 feet; send one call per creature." },
      { name: "volley", label: "Volley", kind: "boolean", help: "Hunter 11: the action makes one ranged attack against each creature within 10 feet of the first; send one call per creature." },
    ],
  },
  {
    name: "enemy_attack",
    label: "Enemy attacks",
    category: "combat",
    summary: "Rolls one enemy attack against a player and applies whatever lands.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Attacker", kind: "enemy", required: true },
      { name: "targetCharacterId", label: "Target", kind: "character", required: true },
      { name: "attack", label: "Attack", kind: "text", help: "Blank picks from the stat block." },
      ...advantageFields(),
    ],
  },
  {
    name: "damage_enemy",
    label: "Damage an enemy",
    category: "combat",
    summary: "Applies damage straight to an enemy, resistances and immunities included.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      { name: "amount", label: "Damage", kind: "number", min: 1, max: 200, help: "Leave empty for a fall." },
      { name: "fallFeet", label: "Falls (feet)", kind: "number", min: 1, max: 1000, help: "The server rolls 1d6 per 10 feet and lays it prone." },
      damageTypeField("type", "Type"),
      { name: "magical", label: "From a spell or a magic weapon", kind: "boolean", help: "Resistance to nonmagical attacks does not apply to it." },
      {
        name: "source",
        label: "Source",
        kind: "select",
        options: [
          { value: "hazard", label: "A hazard (a trap, a falling object)" },
          { value: "environment", label: "The environment (fire, lava, acid)" },
        ],
        help: "The AI DM must name one; the console's own hand may leave it empty.",
      },
      REASON,
    ],
  },
  {
    name: "cast_at_enemy",
    label: "Cast at an enemy",
    category: "combat",
    summary: "A player's save spell against one enemy: the DC comes from the sheet, the dice from the pack when it knows the spell.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Caster", kind: "character", required: true },
      { name: "targetEnemyId", label: "Target", kind: "enemy", required: true },
      { name: "spell", label: "Spell", kind: "text", required: true },
      { name: "saveAbility", label: "Save", kind: "select", options: ABILITIES, help: "A known spell brings its own save; set it for one the server does not know." },
      { name: "level", label: "Slot level", kind: "number", min: 1, max: 9, help: "Leave empty for a cantrip or the spell's own level." },
      { name: "damage", label: "Damage", kind: "dice", placeholder: "3d8", help: "Only for a spell the content pack does not know." },
      damageTypeField("damageType", "Damage type"),
      { name: "halfOnSave", label: "Half on a save", kind: "boolean" },
      conditionField("condition", "Condition on a failed save", { help: "A known spell applies its own; name the one chosen for Blindness/Deafness." }),
      { name: "rounds", label: "Rounds it lasts", kind: "number", min: 1, max: 100 },
      { name: "darts", label: "Magic Missile darts", kind: "number", min: 1, max: 20, help: "How many of the casting's darts strike this enemy. The rest can go to others with no second slot." },
      { name: "endSpell", label: "Dispel Magic ends", kind: "text", help: "The one spell to end when it holds several; empty ends them all." },
      { name: "overchannel", label: "Overchannel", kind: "boolean", help: "An evoker's maximum damage; the server rolls what a second use costs." },
      {
        name: "secondTargetEnemyId",
        label: "Improved Reaper's second enemy",
        kind: "enemy",
        help: "A Death cleric 17: a second enemy within 5 feet of the first, struck by the same necromancy spell from the same slot.",
      },
      // The engine's beast form table, the one the server checks the CR on.
      { name: "variant", label: "Polymorph's beast", kind: "select", options: BEAST_FORMS.map((beast) => ({ value: beast.name.toLowerCase(), label: beast.name })), help: "Polymorph or True Polymorph: what the creature becomes on a failed WIS save, no higher in CR than it." },
      ...AREA_PLACEMENT_FIELDS,
      REASON,
    ],
  },
  {
    name: "cast_at_player",
    label: "Cast at a player",
    category: "combat",
    summary: "An enemy's spell or a trap on one character: the save from their sheet, then the damage or the condition.",
    fields: [
      { name: "characterId", label: "Target", kind: "character", required: true },
      { name: "saveAbility", label: "Save", kind: "select", required: true, options: ABILITIES },
      { name: "dc", label: "Save DC", kind: "number", required: true, min: 1, max: 30 },
      { name: "damage", label: "Damage", kind: "dice", placeholder: "2d6", help: "Give damage, a condition, or both." },
      damageTypeField("damageType", "Damage type"),
      { name: "halfOnSave", label: "Half on a save", kind: "boolean" },
      conditionField("condition", "Condition on a failed save"),
      { name: "rounds", label: "Rounds it lasts", kind: "number", min: 1, max: 100 },
      { name: "casterEnemyId", label: "Enemy doing it", kind: "enemy", help: "Spends its action; its block or spell sets the save, DC and dice." },
      { name: "ability", label: "Its ability", kind: "text", placeholder: "Poison Spit", help: "With an enemy: the name as its block lists it." },
      { name: "spell", label: "Or its spell", kind: "text", help: "With an enemy: one on its list. Its slot is spent and its concentration tracked." },
      { name: "source", label: "Source", kind: "text", placeholder: "a poisoned needle" },
      REASON,
    ],
  },
  {
    name: "cast_buff",
    label: "Cast a buff",
    category: "combat",
    summary: "A helpful spell on the party: the effect lands as a real condition with its duration.",
    fields: [
      { name: "characterId", label: "Caster", kind: "character", required: true },
      { name: "spell", label: "Spell", kind: "text", required: true },
      { name: "targetCharacterIds", label: "Targets", kind: "characters", help: "Empty targets the caster." },
      { name: "level", label: "Slot level", kind: "number", min: 1, max: 9, help: "Empty for a cantrip or the spell's own level." },
      { name: "targetEnemyId", label: "Enemy", kind: "enemy", help: "Hunter's Mark and Hex: the quarry. Dispel Magic: whose spells end. Polymorph: the creature to turn into the beast below. Other buffs refuse an enemy." },
      {
        name: "variant",
        label: "Choice",
        kind: "select",
        // The creatures the summoning spells, Polymorph, Animal Shapes and
        // Shapechange bring, from the engine's own form table, and Find
        // Familiar's forms from the familiar table; the server checks the
        // kind and challenge rating the slot allows, and Pact of the Chain
        // for its four forms.
        options: [...new Set([...summonFormNames(), ...familiarFormNames()])].sort().map((name) => ({ value: name.toLowerCase(), label: name })),
        other: { label: "Another choice", placeholder: "enlarge" },
        help: "A summoning spell's creature, Find Familiar's form, Polymorph's, Animal Shapes' or Shapechange's beast; or type Enlarge/Reduce, Protection from Energy's type, Enhance Ability, Fire Shield.",
      },
      { name: "count", label: "How many", kind: "number", min: 1, max: 40, help: "A summoning spell: fewer creatures than the slot allows; empty for the most." },
      { name: "endSpell", label: "Dispel Magic ends", kind: "text", help: "The one spell to end when the target holds several; empty ends them all." },
      REASON,
    ],
  },
  {
    name: "aoe_damage",
    label: "Area of effect",
    category: "combat",
    summary: "One save, many targets: each rolls, and the halves and evasions resolve themselves.",
    fields: [
      { name: "casterId", label: "Cast by character", kind: "character", help: "A player's spell: the server spends the slot once and derives the dice, save and DC." },
      { name: "spell", label: "Spell", kind: "text", placeholder: "Fireball" },
      { name: "level", label: "Slot level", kind: "number", min: 1, max: 9, help: "Upcasting scales the dice." },
      { name: "casterEnemyId", label: "Or an enemy's", kind: "enemy", help: "Its action; the block or its spell sets the numbers." },
      { name: "ability", label: "Its ability", kind: "text", placeholder: "Fire Breath" },
      { name: "damage", label: "Damage", kind: "dice", placeholder: "8d6", help: "Empty for a spell that deals none (Entangle); a known spell rolls its own." },
      { name: "saveAbility", label: "Save", kind: "select", options: ABILITIES, help: "Needed when no spell is named (a trap); a character's or an enemy's spell brings its own." },
      { name: "dc", label: "DC", kind: "number", min: 1, max: 30, help: "Needed with Save when no spell is named." },
      damageTypeField("type", "Type"),
      { name: "halfOnSave", label: "Half on a save", kind: "boolean", default: true },
      { name: "characterIds", label: "Players caught", kind: "characters" },
      { name: "enemyIds", label: "Enemies caught", kind: "enemies" },
      { name: "targets", label: "Anyone else, by name", kind: "text", placeholder: "the cultist, Brother Aldo", help: "Comma separated, for a creature the pickers do not show." },
      { name: "overchannel", label: "Overchannel", kind: "boolean", help: "An evoker's maximum damage; the server rolls what a second use costs." },
      { name: "sculpt", label: "Sculpted allies", kind: "characters", help: "An evoker's Sculpt Spells: they succeed and take nothing. Empty spares every character caught." },
      ...AREA_PLACEMENT_FIELDS,
      REASON,
    ],
  },
  {
    name: "split_damage",
    label: "Damage tray",
    category: "combat",
    summary: "One rolled total on several creatures, each at full, half, double or none.",
    fields: [
      { name: "amount", label: "Damage rolled", kind: "number", required: true, min: 1, max: 500 },
      damageTypeField("type", "Type"),
      {
        name: "targets",
        label: "Who takes what",
        kind: "shares",
        required: true,
        help: "Each creature at full, half, double or none. Resistances still apply on top.",
      },
      REASON,
    ],
  },
  {
    name: "set_enemy_condition",
    label: "Condition on an enemy",
    category: "combat",
    summary: "Puts a condition on an enemy, with its duration or its save to end.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      conditionField("condition", "Condition", { required: true }),
      { name: "level", label: "Exhaustion level", kind: "number", min: 1, max: 6, help: "Exhaustion only: the level it now has." },
      { name: "rounds", label: "Rounds", kind: "number", min: 1, max: 100 },
      { name: "saveAbility", label: "Save to end", kind: "select", options: ABILITIES },
      { name: "saveDc", label: "Save DC", kind: "number", min: 1, max: 30 },
      { name: "sourceCharacterId", label: "Caused by character", kind: "character", help: "The grappler, the charmer, the source of the fear." },
      { name: "sourceEnemyId", label: "Or by enemy", kind: "enemy" },
      REASON,
    ],
  },
  {
    name: "clear_enemy_condition",
    label: "Clear an enemy condition",
    category: "combat",
    summary: "Takes a condition back off an enemy.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      conditionField("condition", "Condition", { required: true }),
      REASON,
    ],
  },
  {
    name: "enemy_flees",
    label: "An enemy flees",
    category: "combat",
    summary: "Takes an enemy out of the fight alive; the party still earns it.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      REASON,
    ],
  },
  {
    name: "take_action",
    label: "Action",
    category: "combat",
    summary: "Dodge, Dash, Disengage, Hide, Help, Grapple, Shove, Ready, Search, Use an Object or Escape, with its real contest and effect.",
    fields: [
      { name: "characterId", label: "Character", kind: "character", help: "Blank only for an enemy escaping a grapple." },
      {
        name: "action",
        label: "Action",
        kind: "select",
        required: true,
        options: [
          { value: "dodge", label: "Dodge" },
          { value: "dash", label: "Dash" },
          { value: "disengage", label: "Disengage" },
          { value: "hide", label: "Hide" },
          { value: "help", label: "Help" },
          { value: "grapple", label: "Grapple" },
          { value: "shove", label: "Shove" },
          { value: "ready", label: "Ready" },
          { value: "search", label: "Search" },
          { value: "use_object", label: "Use an Object" },
          { value: "escape", label: "Escape a grapple or a spell's hold" },
        ],
      },
      { name: "bonus", label: "As a bonus action", kind: "boolean", help: "Cunning Action, Step of the Wind, Patient Defense." },
      { name: "targetEnemyId", label: "Enemy", kind: "enemy" },
      { name: "targetCharacterId", label: "Ally", kind: "character" },
      { name: "trigger", label: "Readied trigger", kind: "text", placeholder: "when the ogre comes through the door" },
      { name: "spell", label: "Readied spell", kind: "text", placeholder: "Fire Bolt", help: "Ready only: a one-action spell cast now (slot and concentration) and released with the reaction when the trigger comes." },
      { name: "level", label: "Readied spell's slot", kind: "number", min: 1, max: 9, help: "Empty for the spell's own level." },
      {
        name: "skill",
        label: "Search with",
        kind: "select",
        options: [
          { value: "perception", label: "Perception" },
          { value: "investigation", label: "Investigation" },
        ],
      },
      { name: "item", label: "Object", kind: "text" },
      { name: "enemyId", label: "Enemy escaping", kind: "enemy", help: "Escape only, with no character: an enemy breaking a character's grapple, or the spell that holds it (Web, Entangle, Maze's INT check against 20, Irresistible Dance's WIS save)." },
      {
        name: "shove",
        label: "Shove to",
        kind: "select",
        options: [
          { value: "prone", label: "Knock prone" },
          { value: "push", label: "Push away" },
        ],
      },
      REASON,
    ],
  },
  {
    name: "use_reaction",
    label: "Reaction",
    category: "combat",
    summary: "Spends a character's reaction on a named feature and applies what it does.",
    fields: [
      { name: "characterId", label: "Character", kind: "character", required: true },
      {
        name: "feature",
        label: "Feature",
        kind: "select",
        required: true,
        options: REACTIONS,
        other: { label: "Another feature", placeholder: "Sentinel" },
        help: "Answers the last attack against them: a hit that already landed is re-resolved.",
      },
      { name: "targetCharacterId", label: "Ally covered", kind: "character", help: "Protection, Cutting Words, Feather Fall." },
      { name: "targetEnemyId", label: "Enemy answered", kind: "enemy", help: "Hellish Rebuke, Counterspell, Deflect Missiles' throw back." },
      { name: "spell", label: "Spell countered", kind: "text", help: "Counterspell only: the enemy's spell as its block names it." },
      { name: "level", label: "Slot level", kind: "number", min: 1, max: 9, help: "A reaction spell cast from a higher slot; Song of Defense's slot." },
      { name: "x", label: "Move to column", kind: "number", min: 0, max: 200, help: "Skirmisher, Relentless Avenger: the square they move to, drawing no opportunity attacks." },
      { name: "y", label: "Move to row", kind: "number", min: 0, max: 200 },
      REASON,
    ],
  },
  {
    name: "apply_hazard",
    label: "Hazard",
    category: "combat",
    summary: "A fall, a trap, drowning or extreme weather, with the book's damage and saves.",
    fields: [
      {
        name: "type",
        label: "Hazard",
        kind: "select",
        required: true,
        options: [
          { value: "falling", label: "Falling" },
          { value: "trap", label: "Trap" },
          { value: "generic", label: "Something else" },
          { value: "suffocation", label: "Suffocation" },
          { value: "drowning", label: "Drowning" },
          { value: "extreme_cold", label: "Extreme cold" },
          { value: "extreme_heat", label: "Extreme heat" },
        ],
      },
      { name: "characterIds", label: "Caught in it", kind: "characters", required: true },
      { name: "feet", label: "Feet fallen", kind: "number", min: 0, max: 1000 },
      { name: "severity", label: "Trap severity", kind: "select", options: TRAP_SEVERITY_OPTIONS, help: "Sets the save DC and the damage for each victim's level." },
      { name: "hours", label: "Hours of exposure", kind: "number", min: 1, max: 48, help: "Extreme cold or heat: one CON save an hour, a level of exhaustion for each failure." },
      { name: "damage", label: "Damage", kind: "dice", help: "Only for a hazard of your own." },
      damageTypeField("damageType", "Damage type", "Resistances apply."),
      { name: "saveAbility", label: "Save", kind: "select", options: ABILITIES },
      { name: "dc", label: "DC", kind: "number", min: 1, max: 30 },
      { name: "halfOnSave", label: "Half on a save", kind: "boolean", default: true },
      conditionField("condition", "Condition on a failed save"),
      { name: "roundsWithoutAir", label: "Rounds without air", kind: "number", min: 0, max: 100 },
      REASON,
    ],
  },
  {
    name: "end_turn",
    label: "End a turn",
    category: "combat",
    summary: "Ends a character's turn and moves the initiative pointer to the next one.",
    needsEncounter: true,
    fields: [{ name: "characterId", label: "Whose turn", kind: "character", required: true }],
  },
  {
    name: "end_encounter",
    label: "End the fight",
    category: "combat",
    summary: "Closes the encounter, awards XP and hands back half the spent ammunition.",
    needsEncounter: true,
    confirm: { message: "End the fight now? XP is awarded and the board clears; it cannot be reopened." },
    fields: [
      { name: "outcome", label: "Outcome", kind: "text", placeholder: "The party held the bridge" },
      REASON,
    ],
  },
  ...BOARD_ADJUDICATIONS,
];
