// The board half of the combat catalog: pets, tokens on the map, legendary
// creatures and their lairs. Split out of catalog-combat.ts to keep each
// file readable; catalog-combat.ts spreads these into COMBAT_ADJUDICATIONS,
// so every caller still finds one combat list.
import type { CatalogEntry } from "@/lib/dm/catalog-types";
import { REASON_FIELD as REASON } from "@/lib/dm/catalog-vocab";

export const BOARD_ADJUDICATIONS: CatalogEntry[] = [
  {
    name: "summon_pet",
    label: "Summon a pet",
    category: "combat",
    summary: "Gives a character the creature a feature grants them, with its own stat block.",
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      {
        name: "kind",
        label: "Kind",
        kind: "select",
        required: true,
        options: [
          { value: "familiar", label: "Familiar" },
          { value: "beast_companion", label: "Beast companion" },
          { value: "drake", label: "Drake" },
          { value: "other", label: "A pet the story gave them" },
        ],
      },
      { name: "form", label: "Creature", kind: "text", required: true, placeholder: "owl" },
      { name: "name", label: "Name", kind: "text", help: "Blank uses the creature's own." },
      { name: "hp", label: "Hit points", kind: "number", min: 1, max: 300, help: "Only for a pet the story gave them." },
      { name: "ac", label: "Armor Class", kind: "number", min: 1, max: 30, help: "Only for a pet the story gave them." },
      REASON,
    ],
  },
  {
    name: "pet_attack",
    label: "Pet attacks",
    category: "combat",
    summary: "Resolves a pet's attack the same way a player's is resolved.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", help: "Empty when they have only one." },
      { name: "targetEnemyId", label: "Target", kind: "enemy", required: true },
      { name: "attack", label: "Attack", kind: "text" },
    ],
  },
  {
    name: "damage_pet",
    label: "Damage a pet",
    category: "combat",
    summary: "Applies damage to a companion creature.",
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", help: "Empty when they have only one." },
      { name: "amount", label: "Damage", kind: "number", required: true, min: 1, max: 200 },
      REASON,
    ],
  },
  {
    name: "dismiss_pet",
    label: "Dismiss a pet",
    category: "combat",
    summary: "Sends a companion creature away.",
    confirm: { message: "Send the pet away? Its hit points and place on the board are gone with it." },
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", help: "Empty when they have only one." },
      REASON,
    ],
  },
  {
    name: "move_token",
    label: "Move a token",
    category: "combat",
    summary: "Moves a combatant on the map; walls, occupancy and speed still apply.",
    needsEncounter: true,
    fields: [
      {
        name: "tokenName",
        label: "Who moves",
        kind: "combatant",
        required: true,
        other: { label: "A piece by name", placeholder: "Goblin 2" },
        help: "An enemy, or a character being pushed or carried.",
      },
      { name: "x", label: "Column", kind: "number", required: true },
      { name: "y", label: "Row", kind: "number", required: true },
      {
        name: "forced",
        label: "Against their will",
        kind: "boolean",
        help: "On for a shove or a drag; players walk their own tokens otherwise.",
      },
      {
        name: "disengage",
        label: "Disengages first",
        kind: "boolean",
        help: "An enemy leaving reach without opportunity attacks: its bonus action with Nimble Escape, its action otherwise.",
      },
      {
        name: "drag",
        label: "Drags who it grapples",
        kind: "boolean",
        help: "An enemy hauls the character it grapples along at half speed; the grapple holds.",
      },
      REASON,
    ],
  },
  {
    name: "teleport_token",
    label: "Teleport a token",
    category: "combat",
    summary: "Puts a combatant on a tile without a path: Misty Step, a portal, a trap door.",
    fields: [
      {
        name: "tokenName",
        label: "Who",
        kind: "combatant",
        required: true,
        other: { label: "A piece by name", placeholder: "the statue" },
        help: "A character, an enemy, or a piece you placed.",
      },
      { name: "x", label: "Column", kind: "number", required: true },
      { name: "y", label: "Row", kind: "number", required: true },
      { name: "spell", label: "Spell or ability", kind: "text", placeholder: "Misty Step", help: "With a caster below: the server casts it and refuses a jump past its range." },
      { name: "casterId", label: "Cast by character", kind: "character", help: "Spends their slot and the casting time." },
      { name: "casterEnemyId", label: "Or used by enemy", kind: "enemy" },
      {
        name: "cause",
        label: "Or no spell",
        kind: "select",
        options: [{ value: "hazard", label: "A trap door, a portal or another hazard" }],
      },
      {
        name: "rangeFeet",
        label: "Spell range (feet)",
        kind: "number",
        min: 5,
        max: 1000,
        help: "For a spell the server does not know, so a jump past its range is refused.",
      },
      REASON,
    ],
  },
  {
    name: "legendary_action",
    label: "Legendary action",
    category: "combat",
    summary: "A legendary creature spends legendary actions at the end of someone else's turn. The pool refills on its own turn.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Creature", kind: "enemy", required: true },
      { name: "action", label: "Action", kind: "text", required: true, placeholder: "Wing Attack" },
    ],
  },
  {
    name: "declare_intent",
    label: "Declare intent",
    category: "combat",
    summary: "Telegraph what an enemy is about to do; the board shows it over that enemy for the rest of the round.",
    needsEncounter: true,
    fields: [
      { name: "actor", label: "Enemy", kind: "enemy", required: true },
      { name: "verb", label: "Plans to", kind: "text", required: true, placeholder: "Longsword" },
      { name: "target", label: "Mark", kind: "character", help: "Leave empty when there is no single mark." },
      { name: "expected", label: "Expected damage", kind: "number", min: 0, max: 9999, help: "Empty uses the named attack's average. Only seats that see enemy numbers are shown it." },
    ],
  },
  {
    name: "legendary_resist",
    label: "Legendary resistance",
    category: "combat",
    summary: "Turn a failed save into a success while the creature has resistances left.",
    needsEncounter: true,
    fields: [{ name: "enemyId", label: "Creature", kind: "enemy", required: true }],
  },
  {
    name: "lair_action",
    label: "Lair action",
    category: "combat",
    summary: "On initiative 20 the lair itself acts once a round. The fight has to have been started in a lair.",
    needsEncounter: true,
    fields: [{ name: "action", label: "What the lair does", kind: "text", required: true, placeholder: "The floor tilts and grinds" }],
  },
  {
    name: "set_movement",
    label: "Flying or burrowing",
    category: "combat",
    summary: "Marks a combatant as flying, burrowing or back on foot; the board draws it and tremorsense reads it.",
    fields: [
      {
        name: "tokenName",
        label: "Who",
        kind: "combatant",
        required: true,
        other: { label: "A piece by name", placeholder: "Wyvern" },
      },
      {
        name: "movement",
        label: "Now",
        kind: "select",
        required: true,
        options: [
          { value: "walk", label: "On foot" },
          { value: "fly", label: "Flying" },
          { value: "burrow", label: "Burrowing" },
        ],
      },
      REASON,
    ],
  },
];
