// The combat half of the adjudication catalog: everything a DM does with a
// fight running. Names match the tool names the AI DM is offered exactly,
// because both callers reach the same engine
// (src/lib/dm/invoke.ts).
import type { CatalogEntry } from "@/lib/dm/catalog-types";

const ADVANTAGE = [
  { value: "none", label: "Straight" },
  { value: "advantage", label: "Advantage" },
  { value: "disadvantage", label: "Disadvantage" },
];

const ABILITIES = [
  { value: "str", label: "Strength" },
  { value: "dex", label: "Dexterity" },
  { value: "con", label: "Constitution" },
  { value: "int", label: "Intelligence" },
  { value: "wis", label: "Wisdom" },
  { value: "cha", label: "Charisma" },
];

const REASON = {
  name: "reason",
  label: "Reason",
  kind: "text" as const,
  placeholder: "Short in-fiction cause",
};

export const COMBAT_ADJUDICATIONS: CatalogEntry[] = [
  {
    name: "start_encounter",
    label: "Start a fight",
    category: "combat",
    summary: "Rolls initiative for everyone and opens the encounter.",
    fields: [
      {
        name: "enemies",
        label: "Enemies",
        kind: "longtext",
        required: true,
        placeholder: "goblin x4\nhobgoblin",
        help: "One per line, name or SRD slug, optional xN for a count. Stat blocks come from the content pack.",
      },
      { name: "summary", label: "Opening", kind: "text" },
      {
        name: "surprised",
        label: "Surprise",
        kind: "select",
        options: [
          { value: "none", label: "Nobody" },
          { value: "enemies", label: "The enemies are surprised" },
          { value: "party", label: "The party is surprised" },
        ],
      },
      { name: "battlefield", label: "Battlefield", kind: "text" },
    ],
  },
  {
    name: "add_enemies",
    label: "Reinforcements",
    category: "combat",
    summary: "Adds enemies to the fight already running, rolling their initiative in.",
    needsEncounter: true,
    fields: [
      {
        name: "enemies",
        label: "Enemies",
        kind: "longtext",
        required: true,
        placeholder: "wolf x2",
      },
      REASON,
    ],
  },
  {
    name: "pc_attack",
    label: "Player attacks",
    category: "combat",
    summary: "Resolves a player's swing: to hit, damage, crits, riders, all from their sheet.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Attacker", kind: "character", required: true },
      { name: "enemyId", label: "Target", kind: "enemy", required: true },
      { name: "weapon", label: "Weapon", kind: "text", help: "Blank uses what they have equipped." },
      { name: "advantage", label: "Roll", kind: "select", options: ADVANTAGE },
      { name: "maneuver", label: "Maneuver", kind: "text", help: "Battle Master only; spends a Superiority Die." },
    ],
  },
  {
    name: "enemy_attack",
    label: "Enemy attacks",
    category: "combat",
    summary: "Rolls one enemy attack against a player and applies whatever lands.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Attacker", kind: "enemy", required: true },
      { name: "targetCharacterId", label: "Target", kind: "character", required: true },
      { name: "attack", label: "Attack", kind: "text", help: "Blank picks from the stat block." },
      { name: "advantage", label: "Roll", kind: "select", options: ADVANTAGE },
    ],
  },
  {
    name: "damage_enemy",
    label: "Damage an enemy",
    category: "combat",
    summary: "Applies damage straight to an enemy, resistances and immunities included.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      { name: "amount", label: "Damage", kind: "number", required: true, min: 1, max: 200 },
      { name: "type", label: "Type", kind: "text", placeholder: "slashing, fire, ..." },
      REASON,
    ],
  },
  {
    name: "cast_at_enemy",
    label: "Cast at an enemy",
    category: "combat",
    summary: "A player's spell against enemies: the save, the DC and the dice come from the pack.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Caster", kind: "character", required: true },
      { name: "spell", label: "Spell", kind: "text", required: true },
      { name: "enemyIds", label: "Targets", kind: "text", help: "Enemy ids, comma separated." },
      { name: "level", label: "Slot level", kind: "number", min: 0, max: 9 },
    ],
  },
  {
    name: "cast_at_player",
    label: "Cast at a player",
    category: "combat",
    summary: "An enemy's spell at the party: save, damage and any condition, resolved server-side.",
    fields: [
      { name: "spell", label: "Spell", kind: "text", required: true },
      { name: "characterIds", label: "Targets", kind: "characters", required: true },
      { name: "casterEnemyId", label: "Caster", kind: "enemy" },
      { name: "dc", label: "Save DC", kind: "number", min: 1, max: 30 },
    ],
  },
  {
    name: "cast_buff",
    label: "Cast a buff",
    category: "combat",
    summary: "A helpful spell on the party: the effect lands as a real condition with its duration.",
    fields: [
      { name: "characterId", label: "Caster", kind: "character", required: true },
      { name: "spell", label: "Spell", kind: "text", required: true },
      { name: "targetCharacterIds", label: "Targets", kind: "characters" },
      { name: "level", label: "Slot level", kind: "number", min: 0, max: 9 },
    ],
  },
  {
    name: "aoe_damage",
    label: "Area of effect",
    category: "combat",
    summary: "One save, many targets: each rolls, and the halves and evasions resolve themselves.",
    fields: [
      { name: "damage", label: "Damage", kind: "dice", required: true, placeholder: "8d6" },
      { name: "saveAbility", label: "Save", kind: "select", required: true, options: ABILITIES },
      { name: "dc", label: "DC", kind: "number", required: true, min: 1, max: 30 },
      { name: "type", label: "Type", kind: "text", placeholder: "fire" },
      { name: "halfOnSave", label: "Half on a save", kind: "boolean" },
      { name: "characterIds", label: "Players caught", kind: "characters" },
      { name: "enemyIds", label: "Enemies caught", kind: "text", help: "Enemy ids, comma separated." },
    ],
  },
  {
    name: "split_damage",
    label: "Damage tray",
    category: "combat",
    summary: "One rolled total on several creatures, each at full, half, double or none.",
    fields: [
      { name: "amount", label: "Damage rolled", kind: "number", required: true, min: 1, max: 500 },
      { name: "type", label: "Type", kind: "text", placeholder: "fire" },
      {
        name: "targets",
        label: "Who takes what",
        kind: "longtext",
        required: true,
        placeholder: "enemy:goblin-1 full\nenemy:goblin-2 half\ncharacter:<id> none",
        help: "One per line: the id, then full, half, double or none. Resistances still apply on top.",
      },
      REASON,
    ],
  },
  {
    name: "set_enemy_condition",
    label: "Condition on an enemy",
    category: "combat",
    summary: "Puts a condition on an enemy, with its duration or its save to end.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      { name: "condition", label: "Condition", kind: "text", required: true },
      { name: "rounds", label: "Rounds", kind: "number", min: 1, max: 100 },
      { name: "saveAbility", label: "Save to end", kind: "select", options: ABILITIES },
      { name: "saveDc", label: "Save DC", kind: "number", min: 1, max: 30 },
      REASON,
    ],
  },
  {
    name: "clear_enemy_condition",
    label: "Clear an enemy condition",
    category: "combat",
    summary: "Takes a condition back off an enemy.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      { name: "condition", label: "Condition", kind: "text", required: true },
      REASON,
    ],
  },
  {
    name: "enemy_flees",
    label: "An enemy flees",
    category: "combat",
    summary: "Takes an enemy out of the fight alive; the party still earns it.",
    needsEncounter: true,
    fields: [
      { name: "enemyId", label: "Enemy", kind: "enemy", required: true },
      REASON,
    ],
  },
  {
    name: "take_action",
    label: "Action",
    category: "combat",
    summary: "Dodge, Dash, Disengage, Hide, Help, Grapple or Shove, with its real contest and effect.",
    fields: [
      { name: "characterId", label: "Character", kind: "character", required: true },
      {
        name: "action",
        label: "Action",
        kind: "select",
        required: true,
        options: [
          { value: "dodge", label: "Dodge" },
          { value: "dash", label: "Dash" },
          { value: "disengage", label: "Disengage" },
          { value: "hide", label: "Hide" },
          { value: "help", label: "Help" },
          { value: "grapple", label: "Grapple" },
          { value: "shove", label: "Shove" },
        ],
      },
      { name: "targetEnemyId", label: "Enemy", kind: "enemy" },
      { name: "targetCharacterId", label: "Ally", kind: "character" },
      {
        name: "shove",
        label: "Shove to",
        kind: "select",
        options: [
          { value: "prone", label: "Knock prone" },
          { value: "push", label: "Push away" },
        ],
      },
      REASON,
    ],
  },
  {
    name: "use_reaction",
    label: "Reaction",
    category: "combat",
    summary: "Spends a character's reaction on a named feature and applies what it does.",
    fields: [
      { name: "characterId", label: "Character", kind: "character", required: true },
      { name: "feature", label: "Feature", kind: "text", required: true, placeholder: "Shield" },
      { name: "targetCharacterId", label: "Ally covered", kind: "character" },
      REASON,
    ],
  },
  {
    name: "apply_hazard",
    label: "Hazard",
    category: "combat",
    summary: "A fall, a trap, drowning or extreme weather, with the book's damage and saves.",
    fields: [
      {
        name: "type",
        label: "Hazard",
        kind: "select",
        required: true,
        options: [
          { value: "falling", label: "Falling" },
          { value: "trap", label: "Trap" },
          { value: "generic", label: "Something else" },
          { value: "suffocation", label: "Suffocation" },
          { value: "drowning", label: "Drowning" },
          { value: "extreme_cold", label: "Extreme cold" },
          { value: "extreme_heat", label: "Extreme heat" },
        ],
      },
      { name: "characterIds", label: "Caught in it", kind: "characters", required: true },
      { name: "feet", label: "Feet fallen", kind: "number", min: 0, max: 1000 },
      { name: "severity", label: "Trap severity", kind: "text", placeholder: "setback, dangerous, deadly" },
      { name: "damage", label: "Damage", kind: "dice", help: "Only for a hazard of your own." },
      { name: "saveAbility", label: "Save", kind: "select", options: ABILITIES },
      { name: "dc", label: "DC", kind: "number", min: 1, max: 30 },
      { name: "roundsWithoutAir", label: "Rounds without air", kind: "number", min: 0, max: 100 },
      REASON,
    ],
  },
  {
    name: "end_turn",
    label: "End a turn",
    category: "combat",
    summary: "Moves the initiative pointer on from one combatant.",
    needsEncounter: true,
    fields: [{ name: "characterId", label: "Whose turn", kind: "character", required: true }],
  },
  {
    name: "end_encounter",
    label: "End the fight",
    category: "combat",
    summary: "Closes the encounter, awards XP and hands back half the spent ammunition.",
    needsEncounter: true,
    fields: [
      { name: "outcome", label: "Outcome", kind: "text", placeholder: "The party held the bridge" },
      REASON,
    ],
  },
  {
    name: "summon_pet",
    label: "Summon a pet",
    category: "combat",
    summary: "Gives a character a companion creature with its own stat block and turns.",
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "name", label: "Name", kind: "text", required: true },
      { name: "monster", label: "Stat block", kind: "text", placeholder: "wolf" },
    ],
  },
  {
    name: "pet_attack",
    label: "Pet attacks",
    category: "combat",
    summary: "Resolves a pet's attack the same way a player's is resolved.",
    needsEncounter: true,
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", required: true },
      { name: "enemyId", label: "Target", kind: "enemy", required: true },
      { name: "attack", label: "Attack", kind: "text" },
    ],
  },
  {
    name: "damage_pet",
    label: "Damage a pet",
    category: "combat",
    summary: "Applies damage to a companion creature.",
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", required: true },
      { name: "amount", label: "Damage", kind: "number", required: true, min: 1, max: 200 },
      REASON,
    ],
  },
  {
    name: "dismiss_pet",
    label: "Dismiss a pet",
    category: "combat",
    summary: "Sends a companion creature away.",
    fields: [
      { name: "characterId", label: "Owner", kind: "character", required: true },
      { name: "petName", label: "Pet", kind: "text", required: true },
      REASON,
    ],
  },
  {
    name: "move_token",
    label: "Move a token",
    category: "combat",
    summary: "Moves a combatant on the map; walls, occupancy and speed still apply.",
    needsEncounter: true,
    fields: [
      {
        name: "tokenName",
        label: "Who moves",
        kind: "text",
        required: true,
        placeholder: "Goblin 2",
        help: "An enemy name, or a character being pushed or carried.",
      },
      { name: "x", label: "Column", kind: "number", required: true },
      { name: "y", label: "Row", kind: "number", required: true },
      {
        name: "forced",
        label: "Against their will",
        kind: "boolean",
        help: "On for a shove or a drag; players walk their own tokens otherwise.",
      },
      REASON,
    ],
  },
];
