// The built-in list of leveled spells the narration guard
// (src/lib/dm/engine-boundary.ts) checks a "casts" claim against when the
// caller brings no spell data of its own. Plain data with no imports, so the
// guard stays importable on its own; the guard normalizes the names.

// Only leveled SRD spells whose casting genuinely costs a slot. Cantrips are
// absent on purpose: casting one spends nothing, so their absence from the
// turn's tool calls would prove nothing.
export const LEVELED_SPELL_NAMES = [
  "burning hands",
  "charm person",
  "cure wounds",
  "detect magic",
  "disguise self",
  "faerie fire",
  "false life",
  "feather fall",
  "find familiar",
  "fog cloud",
  "healing word",
  "hellish rebuke",
  "hex",
  "hunter's mark",
  "identify",
  "inflict wounds",
  "magic missile",
  "mage armor",
  "protection from evil and good",
  "shield of faith",
  "sleep",
  "thunderwave",
  "bless",
  "bane",
  "aid",
  "blur",
  "darkness",
  "enhance ability",
  "hold person",
  "invisibility",
  "lesser restoration",
  "levitate",
  "mirror image",
  "misty step",
  "moonbeam",
  "pass without trace",
  "scorching ray",
  "shatter",
  "silence",
  "spike growth",
  "spiritual weapon",
  "suggestion",
  "web",
  "animate dead",
  "bestow curse",
  "call lightning",
  "counterspell",
  "dispel magic",
  "fear",
  "fireball",
  "fly",
  "haste",
  "hypnotic pattern",
  "lightning bolt",
  "mass healing word",
  "revivify",
  "sleet storm",
  "slow",
  "spirit guardians",
  "stinking cloud",
  "vampiric touch",
  "banishment",
  "blight",
  "confusion",
  "dimension door",
  "greater invisibility",
  "ice storm",
  "polymorph",
  "wall of fire",
  "cloudkill",
  "cone of cold",
  "dominate person",
  "flame strike",
  "hold monster",
  "mass cure wounds",
  "raise dead",
  "wall of force",
  "chain lightning",
  "disintegrate",
  "sunbeam",
  "true seeing",
  "finger of death",
  "plane shift",
  "resurrection",
  "teleport",
  "dominate monster",
  "power word stun",
  "sunburst",
  "meteor swarm",
  "power word kill",
  "time stop",
  "wish",
];
